server:
  port: 7060

servicedata:
  api:
    username: a2si-servicedata-api-user
    password: EyeDeeTee

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/IDT_DB
    username: idt_user
    password: password
